name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: |
          javac src/Main.java  # Adjust path as needed

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./src/*.class  # Adjust this path to include the compiled .class files

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: |
          echo "No tests to run"  # Replace with actual test commands when ready

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: .

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."  # Replace with actual deployment commands

  notify:
    name: Notify Teams on Build Success
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Notify Microsoft Teams
        run: |
          curl -H 'Content-Type: application/json' \
               -d '{
                 "@type": "MessageCard",
                 "@context": "https://schema.org/extensions",
                 "themeColor": "0076D7",
                 "title": "Build Successful",
                 "text": "The build for commit '"${GITHUB_SHA}"' was successful!",
                 "sections": [{
                   "facts": [
                     {
                       "name": "Repository:",
                       "value": "'"${GITHUB_REPOSITORY}"'"
                     },
                     {
                       "name": "Commit:",
                       "value": "'"${GITHUB_SHA}"'"
                     },
                     {
                       "name": "Build URL:",
                       "value": "'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"'"
                     }
                   ]
                 }]
               }' \
               ${{ secrets.TEAMS_WEBHOOK_URL }}
